### ISSUE TITLE
Couldn't find upload_bypass.py

### ISSUE THREAD

**Issue by KreativeNerd** [sAjibuu/upload_bypass_carnage#3]
I git cloned and installed the program but couldn't find upload_bypass.py. Please where is the upload_bypass.py located?

**Comment by sAjibuu** [comment]
Download it from the Releases page.

**Comment by rebrec** [comment]
Why not provide the code directly within the github repo ?
If someone wants to make a pull request, he won't be able to do it naturally by simply clonning the repo.

**Comment by sAjibuu** [comment]
> Why not provide the code directly within the github repo ? If someone wants to make a pull request, he won't be able to do it naturally by simply clonning the repo.

The update feature I implemented is pulling the latest version of the tool from the "Releases Page" and not from the branch itself. Therefore I don't see any reason to upload each update in the main branch as well, it should be easy enough to download the tool for the first time from the releases page anyway...

**Comment by tanguySnoeck** [comment]
@rebrec's comment has nothing to do with the way you handle releases or "updates". The release feature of github is only meant to make stable releases easily accessible. 
Please publish the entire source code of the project, that's how open-source works. Otherwise, no one will be able to contribute to your project by making PRs. In that case, the only thing people can do is download your project, take your source and create a clone of your project on another repo.

**Comment by sAjibuu** [comment]
> @rebrec's comment has nothing to do with the way you handle releases or "updates". The release feature of github is only meant to make stable releases easily accessible. Please publish the entire source code of the project, that's how open-source works. Otherwise, no one will be able to contribute to your project by making PRs. In that case, the only thing people can do is download your project, take your source and create a clone of your project on another repo.

I will publish the source code of the project soon enough!
I'm working on a newer version of the tool, should be more readable, stable and modular with new features.
Thanks for the suggestion.
